status = warn
name = PropertiesConfig

# 1. 콘솔 Appender 설정
appender.console.type = Console
appender.console.name = LogToConsole
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c{1} = %m%n

# 2. 파일 Appender 설정
appender.file.type = File
appender.file.name = LogToFile

# 원하는 파일 경로 및 이름 설정
appender.file.fileName = C:/Users/Moai/WOORIFISA/ce06/logs/${date:yyyy-MM-dd}.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c{1} = %m%n

# true면 기존 내용 뒤에 이어쓰기, false면 실행 때마다 새로 덮어쓰기
appender.file.append = true

# 3. Root Logger 설정 (콘솔 + 파일 둘 다 연결)
rootLogger.level = debug
# 콘솔에 출력
rootLogger.appenderRef.stdout.ref = LogToConsole
# 파일에 저장 
rootLogger.appenderRef.file.ref = LogToFile